# Generated by Django 3.0.2 on 2020-06-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200612_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='password',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
