# Generated by Django 3.0.2 on 2020-06-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200615_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
