# Generated by Django 3.0.2 on 2020-06-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quizanswer_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='minutes',
            field=models.IntegerField(default=30),
        ),
    ]
